package com.example.bookstore.Dto; // Ensure this package is correct

import java.time.LocalDate;

public class BookResponseDTO {
    private Long id;
    private String title;
    private String isbn;
    private Double price; // Note: Ensure this is Double, not double if you need nullability
    private LocalDate publicationDate;

    // --- Constructors ---
    // This is the no-argument constructor, generated by @NoArgsConstructor if you use Lombok here,
    // or you can write it explicitly if not using Lombok for DTOs.
    public BookResponseDTO() {}

    // This is the all-argument constructor that your controller is trying to call.
    // It must have 5 arguments matching the fields: id, title, isbn, price, publicationDate.
    public BookResponseDTO(Long id, String title, String isbn, Double price, LocalDate publicationDate) {
        this.id = id;
        this.title = title;
        this.isbn = isbn;
        this.price = price;
        this.publicationDate = publicationDate;
    }

    // --- Getters and Setters ---
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }
    public String getIsbn() { return isbn; }
    public void setIsbn(String isbn) { this.isbn = isbn; }
    public Double getPrice() { return price; }
    public void setPrice(Double price) { this.price = price; }
    public LocalDate getPublicationDate() { return publicationDate; }
    public void setPublicationDate(LocalDate publicationDate) { this.publicationDate = publicationDate; }
}